export const musicas = [
  {
    id: '1',
    titulo: 'Life is a Highway',
    artista: 'Rascal Flatts',
    album: 'Cars Soundtrack',
    duracao: '4:36',
    genero: 'Country Rock',
    ano: '2006',
    favorito: true,
  },
  {
    id: '2',
    titulo: 'Real Gone',
    artista: 'Sheryl Crow',
    album: 'Cars Soundtrack',
    duracao: '3:22',
    genero: 'Rock',
    ano: '2006',
    favorito: false,
  },
  {
    id: '3',
    titulo: 'Route 66',
    artista: 'Chuck Berry',
    album: 'Cars Soundtrack',
    duracao: '2:52',
    genero: 'Rock and Roll',
    ano: '2006',
    favorito: true,
  },
  {
    id: '4',
    titulo: 'Find Yourself',
    artista: 'Brad Paisley',
    album: 'Cars Soundtrack',
    duracao: '4:11',
    genero: 'Country',
    ano: '2006',
    favorito: false,
  },
  {
    id: '5',
    titulo: 'Behind the Clouds',
    artista: 'Brad Paisley',
    album: 'Cars Soundtrack',
    duracao: '3:33',
    genero: 'Country',
    ano: '2006',
    favorito: true,
  },
  {
    id: '6',
    titulo: 'Our Town',
    artista: 'James Taylor',
    album: 'Cars Soundtrack',
    duracao: '4:04',
    genero: 'Folk Rock',
    ano: '2006',
    favorito: false,
  },
  {
    id: '7',
    titulo: 'Sh-Boom',
    artista: 'The Chords',
    album: 'Cars Soundtrack',
    duracao: '2:27',
    genero: 'Doo-Wop',
    ano: '1954',
    favorito: true,
  },
  {
    id: '8',
    titulo: 'Opening Race',
    artista: 'Randy Newman',
    album: 'Cars Original Score',
    duracao: '2:15',
    genero: 'Instrumental',
    ano: '2006',
    favorito: false,
  },
];